spring.application.name=pbl

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/likelion_pbl?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0091}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:local-test-secret-key-local-test-secret-key-1234567890}